import { motion } from "framer-motion";
import { Link } from "react-router-dom";
import Navbar from "../components/Navbar";

const LAST_UPDATED = "April 3, 2025";

const sections = [
  {
    id: "agreement",
    title: "Agreement to Terms",
    content: `By accessing trecc.finance, connecting a wallet to the TRECC web application, or interacting with any TRECC smart contract deployed on Ethereum Sepolia or Base Sepolia, you agree to be bound by these Terms of Service ("Terms") and our Privacy Policy, which is incorporated herein by reference.

If you do not agree to these Terms, do not access or use the protocol. TRECC Labs, Inc. ("TRECC", "we", "our") reserves the right to modify these Terms at any time. Continued use after changes are posted constitutes acceptance.`,
  },
  {
    id: "protocol-description",
    title: "Protocol Description",
    content: `TRECC is a non-custodial, decentralised lending protocol that enables autonomous AI agents ("Agents") — identified via ERC-8004 soulbound NFTs — to access undercollateralised USDC credit lines. Capital is supplied by lenders who deposit USDC into TRECVault. Operators post ETH bonds and register Agents through TRECIdentityRegistry. Credit eligibility is determined by on-chain reputation scores stored in TRECReputationRegistry and cryptographic KYC signatures verified by TRECValidationRegistry.

The TRECC interface is a front-end convenience layer. The underlying smart contracts are autonomous and function independently of TRECC Labs.`,
  },
  {
    id: "eligibility",
    title: "Eligibility",
    subsections: [
      {
        label: "Age & capacity",
        text: "You must be at least 18 years old and have full legal capacity to enter into binding agreements in your jurisdiction.",
      },
      {
        label: "Prohibited jurisdictions",
        text: "You may not use TRECC if you are located in, or a resident or national of, any country subject to comprehensive sanctions by the United States, European Union, or United Nations, including but not limited to Iran, North Korea, Cuba, Syria, and the Crimea region.",
      },
      {
        label: "Compliance",
        text: "You are solely responsible for ensuring your use of TRECC complies with all applicable laws and regulations in your jurisdiction, including those governing securities, commodities, and money transmission.",
      },
    ],
  },
  {
    id: "protocol-risks",
    title: "Protocol Risks",
    content: `Interacting with TRECC involves significant financial risk. By using the protocol you acknowledge and accept the following:`,
    items: [
      "Smart contract risk — bugs or vulnerabilities in TRECC contracts or third-party dependencies may result in partial or total loss of funds.",
      "Undercollateralisation risk — loans issued to Agents are intentionally undercollateralised. If an Agent defaults and the ETH bond is insufficient to cover the shortfall, lenders may suffer losses.",
      "Liquidation risk — operator ETH bonds are subject to slashing (−50 credit score, bond seizure) if an Agent fails to repay. Lenders bear residual shortfall risk.",
      "Market risk — the value of ETH bonds denominated in USD fluctuates. A sharp ETH price drop may reduce bond coverage before liquidation can occur.",
      "Regulatory risk — the legal status of decentralised lending protocols and AI agents is unsettled in many jurisdictions and may change.",
      "Key compromise — loss or theft of your private keys results in permanent loss of on-chain assets. TRECC cannot recover funds.",
      "Network risk — blockchain congestion, forks, or validator failures may delay or prevent transactions.",
    ],
  },
  {
    id: "lender-terms",
    title: "Lender Terms",
    content: `Lenders deposit USDC into TRECVault to earn interest generated by Agent loan repayments. By depositing you acknowledge:`,
    items: [
      "Deposits are deployed into undercollateralised loans and are not guaranteed.",
      "APY figures displayed in the interface are estimates derived from current utilisation and are not promises of future returns.",
      "Withdrawals may be delayed if vault utilisation is at 100% — liquidity becomes available as loans are repaid.",
      "TRECC Labs does not hold, custody, or insure your deposited USDC at any time.",
    ],
  },
  {
    id: "operator-terms",
    title: "Operator & Agent Terms",
    content: `Operators register AI Agents and post ETH bonds to access credit. By registering an Agent you agree to:`,
    items: [
      "Post and maintain the required ETH bond as specified in TRECVault at time of registration.",
      "Ensure your Agent operates within its declared scope and does not execute transactions beyond its whitelisted parameters.",
      "Accept that your ETH bond may be partially or fully slashed if your Agent defaults on a loan.",
      "Accept that the soulbound identity NFT (ERC-8004) issued to your Agent cannot be transferred or burned and will reflect all on-chain credit activity permanently.",
      "Not attempt to circumvent credit scoring by registering multiple identities for the same Agent.",
    ],
  },
  {
    id: "prohibited-uses",
    title: "Prohibited Uses",
    content: `You agree not to use the TRECC protocol or interface to:`,
    items: [
      "Launder money, finance terrorism, or conduct any activity in violation of applicable anti-money-laundering (AML) or counter-terrorist financing (CTF) laws.",
      "Manipulate credit scores through artificial repayment cycles or wash trading.",
      "Deploy Agents designed to intentionally default on loans to drain vault liquidity.",
      "Exploit smart contract vulnerabilities — any discovered vulnerability must be disclosed responsibly to trecclabs@gmail.com.",
      "Scrape, mirror, or frame the TRECC interface without written permission.",
      "Interfere with or disrupt the protocol's infrastructure or connected services.",
    ],
  },
  {
    id: "intellectual-property",
    title: "Intellectual Property",
    content: `The TRECC web interface, branding, and documentation are the intellectual property of TRECC Labs, Inc. The smart contracts are open-source and released under the MIT licence — you may fork and deploy them subject to that licence's terms.

"TRECC", the TRECC logo, and "trecc.eth" are trademarks of TRECC Labs, Inc. and may not be used without prior written consent.`,
  },
  {
    id: "disclaimers",
    title: "Disclaimers",
    content: `THE TRECC PROTOCOL AND INTERFACE ARE PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT.

TRECC LABS DOES NOT WARRANT THAT THE PROTOCOL WILL BE UNINTERRUPTED, ERROR-FREE, OR FREE OF HARMFUL COMPONENTS. WE MAKE NO REPRESENTATION REGARDING THE SUITABILITY OF THE PROTOCOL FOR ANY PARTICULAR PURPOSE.

NOTHING IN THESE TERMS CONSTITUTES FINANCIAL, INVESTMENT, LEGAL, OR TAX ADVICE. YOU ARE SOLELY RESPONSIBLE FOR YOUR OWN INVESTMENT DECISIONS.`,
  },
  {
    id: "limitation-of-liability",
    title: "Limitation of Liability",
    content: `TO THE MAXIMUM EXTENT PERMITTED BY LAW, TRECC LABS, ITS DIRECTORS, EMPLOYEES, CONTRACTORS, AND AFFILIATES SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING LOSS OF FUNDS, PROFITS, DATA, OR GOODWILL, ARISING OUT OF OR IN CONNECTION WITH YOUR USE OF THE PROTOCOL.

IN JURISDICTIONS THAT DO NOT ALLOW THE EXCLUSION OF CERTAIN WARRANTIES OR LIMITATIONS OF LIABILITY, OUR LIABILITY IS LIMITED TO THE MAXIMUM EXTENT PERMITTED BY LAW.`,
  },
  {
    id: "governing-law",
    title: "Governing Law & Disputes",
    content: `These Terms are governed by the laws of the State of Delaware, United States, without regard to conflict-of-law principles. Any dispute arising from these Terms or your use of the protocol shall first be submitted to good-faith negotiation. If unresolved within 30 days, disputes shall be settled by binding arbitration under the rules of the American Arbitration Association (AAA), with proceedings conducted in English.

You waive any right to participate in a class-action lawsuit or class-wide arbitration.`,
  },
  {
    id: "contact",
    title: "Contact",
    content: `For legal inquiries or questions about these Terms, contact us at trecclabs@gmail.com or through the contact form at trecc.finance/contact.`,
  },
];

export default function TermsOfServicePage() {
  return (
    <div className="min-h-screen w-full bg-[#030303] text-white font-sans relative overflow-x-hidden">
      <Navbar isLightMode={false} />

      <main className="relative z-10 min-h-screen px-6 pt-32 pb-24">
        <div className="w-full max-w-3xl mx-auto">

          {/* Header */}
          <motion.div
            initial={{ opacity: 0, y: 32 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.7, ease: [0.16, 1, 0.3, 1] }}
            className="mb-14"
          >
            <div className="inline-block px-3 py-1 mb-5 rounded-full border border-white/10 bg-white/5 text-xs font-mono text-[#8A8D93] uppercase tracking-widest">
              Legal
            </div>
            <h1 className="text-chrome font-medium tracking-tight leading-tight mb-4 text-4xl sm:text-5xl">
              Terms of Service
            </h1>
            <p className="text-[#8A8D93] text-sm font-mono">
              Last updated: {LAST_UPDATED}
            </p>
          </motion.div>

          {/* Table of Contents */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, delay: 0.1, ease: [0.16, 1, 0.3, 1] }}
            className="hyper-card p-6 mb-10"
          >
            <p className="text-xs text-[#8A8D93] font-semibold uppercase tracking-widest mb-4">Contents</p>
            <ol className="space-y-2">
              {sections.map((s, i) => (
                <li key={s.id}>
                  <a
                    href={`#${s.id}`}
                    className="flex items-center gap-3 text-sm text-[#606468] hover:text-[#d7d7b6] transition-colors duration-200 group"
                  >
                    <span className="font-mono text-[10px] text-white/20 group-hover:text-[#d7d7b6]/40 w-4 shrink-0">
                      {String(i + 1).padStart(2, "0")}
                    </span>
                    {s.title}
                  </a>
                </li>
              ))}
            </ol>
          </motion.div>

          {/* Sections */}
          <div className="space-y-6">
            {sections.map((s, i) => (
              <motion.div
                key={s.id}
                id={s.id}
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.5, delay: 0.15 + i * 0.04, ease: [0.16, 1, 0.3, 1] }}
                className="hyper-card p-6"
              >
                <div className="flex items-start gap-4 mb-4">
                  <span className="font-mono text-[10px] text-white/20 mt-1 shrink-0">
                    {String(i + 1).padStart(2, "0")}
                  </span>
                  <h2 className="text-white font-semibold text-base tracking-tight">{s.title}</h2>
                </div>

                <div className="pl-8 space-y-4">
                  {s.content && (
                    <p className="text-[#8A8D93] text-sm leading-relaxed whitespace-pre-line">{s.content}</p>
                  )}

                  {s.subsections && (
                    <div className="space-y-3">
                      {s.subsections.map((sub) => (
                        <div key={sub.label} className="border-l border-white/[0.06] pl-4">
                          <p className="text-xs font-semibold text-white/60 uppercase tracking-widest mb-1">{sub.label}</p>
                          <p className="text-[#8A8D93] text-sm leading-relaxed">{sub.text}</p>
                        </div>
                      ))}
                    </div>
                  )}

                  {s.items && (
                    <ul className="space-y-2">
                      {s.items.map((item, j) => (
                        <li key={j} className="flex items-start gap-2.5 text-sm text-[#8A8D93] leading-relaxed">
                          <span className="mt-1.5 w-1 h-1 rounded-full bg-white/20 shrink-0" />
                          {item}
                        </li>
                      ))}
                    </ul>
                  )}
                </div>
              </motion.div>
            ))}
          </div>

          {/* Related links */}
          <motion.div
            initial={{ opacity: 0, y: 16 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5, delay: 0.65 }}
            className="mt-10 hyper-card p-5 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4"
          >
            <p className="text-xs text-[#606468]">
              Also see our{" "}
              <Link to="/privacy" className="text-[#d7d7b6] hover:text-white transition-colors underline underline-offset-2">
                Privacy Policy
              </Link>
            </p>
            <Link
              to="/"
              className="inline-flex items-center gap-2 text-sm text-[#606468] hover:text-white transition-colors duration-200 group shrink-0"
            >
              <svg className="w-4 h-4 group-hover:-translate-x-0.5 transition-transform" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                <path strokeLinecap="round" strokeLinejoin="round" d="M10 19l-7-7m0 0l7-7m-7 7h18" />
              </svg>
              Back to home
            </Link>
          </motion.div>
        </div>
      </main>

      <div className="relative z-10 border-t border-white/5 py-5 px-6 text-center">
        <p className="text-xs text-[#50545a]">© {new Date().getFullYear()} TRECC Labs, Inc.</p>
      </div>
    </div>
  );
}
